/* Generated By:JavaCC: Do not edit this line. C0Language.java */
package c0.parser;

import c0.ast.*;
import c0.util.*;
import java.util.List;
import java.util.LinkedList;

public class C0Language implements C0LanguageConstants {

        private String fileName = null;
        private List<Identifier> symbolTable = null;

        public String getFileName() {
                return fileName;
        }

        public void setFileName(String fileName) {
                this.fileName = fileName;
        }

        public List<Identifier> getSymbolTable() {
                return symbolTable;
        }

        public void setSymbolTable(List<Identifier> symbolTable) {
                this.symbolTable = symbolTable;
        }

//„Éë„?„Çµ„ÅÆË®òËø∞

//Â§ñÈÉ®ÂÆ£Ë®?:=
//   {Èñ¢Êï∞ÂÆ£Ë®?+
//	|Â§ñÈÉ®Â§âÊï∞ÂÆ£Ë®?
  final public AstNode file() throws ParseException {
        Token token = null;
        List<IdentifierNode> functions = new LinkedList<IdentifierNode>();
        IdentifierNode function = null;
        List<DeclareVariableNode> globalVariables = new LinkedList<DeclareVariableNode>();
        DeclareVariableNode globalVariable = null;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INT:
      case VOID:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      try {
        if (jj_2_1(2147483647)) {
          function = defineFunction();
                                                  if(function != null) functions.add(function);
        } else {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case INT:
          case VOID:
            globalVariable = declareVariable();
                                                             if(globalVariable != null) globalVariables.add(globalVariable);
            break;
          default:
            jj_la1[1] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      } catch (ParseException e) {
                        e.printStackTrace();

                                //Êñ??„Éï„Ç°„Ç§„É´„ÅÆÁµÇ„Çè„Çä„ÅåË¶ã„Å§„Åã„Çã„Åæ„Åß„Çπ„Ç≠„É??„Åô„Çã
                                //„Åì„?Âá¶Áê?Å´„Éê„Ç∞„Åå„Å™„Å?Åã„ÉÅ„Çß„É?ÇØ„Åô„Çã
                                do {
                                        token = getNextToken();
                                } while(token.image.equals(";") && token.image.equals("}") && token.kind != EOF);
      }
    }
    jj_consume_token(0);
                                {if (true) return new AstNode(globalVariables, functions);}
    throw new Error("Missing return statement in function");
  }

//Èñ¢Êï∞ÂÆ£Ë®?:=
//	„É??„ÇøÂû?ÂçòÁ¥îÂÆ£Ë®?≠?'(' [ÂºïÊï∞ {',' ÂºïÊï∞}* ] ')' Ë§?êàÊñ?
  final public IdentifierNode defineFunction() throws ParseException {
        DataTypeNode dataType = null;
        ExpressionNode function = null;
        IdentifierNode function_i = null;
        List<ParameterNode> parameters = null;
        StatementNode block = null;
        Identifier identifier = null;
    dataType = type();
    function = primaryExpression();
    jj_consume_token(17);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
    case VOID:
      parameters = parameters();
      break;
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    jj_consume_token(18);
    block = blockStatement();
                        function_i = (IdentifierNode)function;

                        identifier = function_i.getIdentifier();
                        identifier.setIdentifierType(IdentifierType.FUNCTION); //Ë≠òÂà•Â≠ê„?Á®ÆÈ°û„?Èñ¢Êï∞
                        identifier.setStandardFunctionFlag(false); //Áµ?ÅøËæº„ÅøÈñ¢Êï∞„Åß„ÅØ„Å™„Å?
                        function_i.setIdentifier(identifier);

                        function_i.setParameters(parameters); //ÂºïÊï∞
                        function_i.setBlock(block); //Ë§?êàÊñ?
                        function_i.setReturnDataType(dataType); //Êàª„ÇäÂ?„ÅÆ„É??„ÇøÂû?
                        {if (true) return function_i;}
    throw new Error("Missing return statement in function");
  }

//ÂºïÊï∞„ÅÆ„É™„Çπ„É?
  final public List<ParameterNode> parameters() throws ParseException {
        List<ParameterNode> parameters = new LinkedList<ParameterNode>();
        ParameterNode parameter1 = null;
        ParameterNode parameter2 = null;
    parameter1 = parameter();
                                 if(parameter1 != null) parameters.add(parameter1);
    label_2:
    while (true) {
      if (jj_2_2(2)) {
        ;
      } else {
        break label_2;
      }
      jj_consume_token(19);
      parameter2 = parameter();
                                                   if(parameter2 != null) parameters.add(parameter2);
    }
                {if (true) return parameters;}
    throw new Error("Missing return statement in function");
  }

//ÂºïÊï∞ :=
//	„É??„ÇøÂû?Ë≠òÂà•Â≠?
  final public ParameterNode parameter() throws ParseException {
        Token token = null;
        DataTypeNode dataType = null;
        ExpressionNode parameterName = null;
        IdentifierNode parameterName_i = null;
        Identifier identifier = null;
    dataType = type();
    parameterName = primaryExpression();
                        parameterName_i = (IdentifierNode)parameterName;
                        identifier = parameterName_i.getIdentifier();
                        identifier.setIdentifierType(IdentifierType.VARIABLE); //Ë≠òÂà•Â≠ê„?Á®ÆÈ°û„?Â§âÊï∞
                        parameterName_i.setIdentifier(identifier);
                        {if (true) return new ParameterNode(new Location(this.getFileName(), token), dataType, parameterName_i);}
    throw new Error("Missing return statement in function");
  }

//Â§âÊï∞ÂÆ£Ë®?:=
//„É??„ÇøÂû?ÂçòÁ¥îÂÆ£Ë®?≠?['=' Âºè] ';'
//|„É??„ÇøÂû?ÈÖçÂ?ÂÆ£Ë®?≠?';'
  final public DeclareVariableNode declareVariable() throws ParseException {
        Token token = null;
        DataTypeNode dataType = null;
        ExpressionNode variable = null;
        IdentifierNode variable_i = null;
        ExpressionNode expression = null;
        Identifier identifier = null;
    dataType = type();
    variable = primaryExpression();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 20:
      jj_consume_token(20);
      expression = expression();
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    token = jj_consume_token(21);
                        variable_i = (IdentifierNode)variable;
                        identifier = variable_i.getIdentifier();
                        identifier.setIdentifierType(IdentifierType.VARIABLE); //Ë≠òÂà•Â≠ê„?Á®ÆÈ°û„?Â§âÊï∞
                        variable_i.setIdentifier(identifier);
                        {if (true) return new DeclareVariableNode(new Location(this.getFileName(), token), dataType, variable_i, expression);}
    throw new Error("Missing return statement in function");
  }

//Âûã„?ÊßãÊñá
//„É??„ÇøÂû?:=
//	'int'
  final public DataTypeNode type() throws ParseException {
        DataType dataType; //Âü∫Êú¨„É??„ÇøÂû?
        ExpressionNode elementNumber = null;
    if (jj_2_3(2147483647)) {
      jj_consume_token(INT);
      jj_consume_token(22);
      elementNumber = expression();
      jj_consume_token(23);
                {if (true) return new DataTypeNode(DataType.INT_ARRAY, elementNumber);} //Êï¥Êï∞„ÅÆÈÖçÂ?

    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INT:
        jj_consume_token(INT);
                {if (true) return new DataTypeNode(DataType.INT, elementNumber);} //Êï¥Êï∞„ÅÆÂ§âÊï∞

        break;
      case VOID:
        jj_consume_token(VOID);
                {if (true) return new DataTypeNode(DataType.VOID, elementNumber);} //void

        break;
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

//Êñ?:=
//	ÂºèÊñá
//	|Ë§?êàÊñ?
//	|Êù°‰ª∂Êñ?
//	|Áπ∞„ÇäËøî„ÅóÊñ?
//	|returnÊñ?
//	|Á©∫Êñ?
  final public StatementNode statement() throws ParseException {
        StatementNode statementNode = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
    case INTEGER:
    case STRING:
    case 17:
    case 35:
    case 39:
    case 40:
    case 41:
      statementNode = expressionStatement();
      break;
    case 24:
      statementNode = blockStatement();
      break;
    case IF:
      statementNode = conditionalStatement();
      break;
    case WHILE:
    case FOR:
      statementNode = iterationStatement();
      break;
    case BREAK:
      statementNode = breakStatement();
      break;
    case RETURN:
      statementNode = returnStatement();
      break;
    case 21:
      statementNode = emptyStatement();
      break;
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                        {if (true) return statementNode;}
    throw new Error("Missing return statement in function");
  }

//Ë§?êàÊñ?:=
//	'{' Â±?âÄÂ§âÊï∞ÂÆ£Ë®?{Êñ?* '}'
  final public StatementNode blockStatement() throws ParseException {
        Token token = null;
        List<DeclareVariableNode> localVariables = null; //„É≠„Éº„Ç´„É´Â§âÊï∞„ÅÆÂÆ£Ë®?
        List<StatementNode> statements = null;
    token = jj_consume_token(24);
    localVariables = declareLocalVariables();
    statements = statements();
    jj_consume_token(25);
                {if (true) return new BlockNode(new Location(this.getFileName(), token), localVariables, statements);}
    throw new Error("Missing return statement in function");
  }

//„Éñ„É≠„É?ÇØÊñ?ú¨‰Ω?
  final public List<StatementNode> statements() throws ParseException {
        List<StatementNode> statements = new LinkedList<StatementNode>(); //Êñ??„É™„Çπ„É?
        StatementNode statement = null;
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IF:
      case WHILE:
      case FOR:
      case RETURN:
      case BREAK:
      case IDENTIFIER:
      case INTEGER:
      case STRING:
      case 17:
      case 21:
      case 24:
      case 35:
      case 39:
      case 40:
      case 41:
        ;
        break;
      default:
        jj_la1[6] = jj_gen;
        break label_3;
      }
      statement = statement();
                                 if(statement != null) statements.add(statement);
    }
                {if (true) return statements;}
    throw new Error("Missing return statement in function");
  }

//Â±?âÄÂ§âÊï∞ÂÆ£Ë®?:=
//	{Â§âÊï∞ÂÆ£Ë®?+
  final public List<DeclareVariableNode> declareLocalVariables() throws ParseException {
        List<DeclareVariableNode> declareVariables = new LinkedList<DeclareVariableNode>(); //„Åô„Åπ„Å¶„ÅÆÂ±?âÄÂ§âÊï∞ÂÆ£Ë®?
        DeclareVariableNode declareVar = null;
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INT:
      case VOID:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_4;
      }
      declareVar = declareVariable();
                                        if(declareVar != null) declareVariables.add(declareVar);
    }
                {if (true) return declareVariables;}
    throw new Error("Missing return statement in function");
  }

//Êù°‰ª∂Êñ?:=
//	ifÊñ?
//„Åì„?ÁÆ?âÄ„ÅØÂâäÈô§„Åô„Çã„ÅãÊ§úË®é„Åô„Ç?
  final public StatementNode conditionalStatement() throws ParseException {
        StatementNode conditionalStatementNode = null;
    conditionalStatementNode = ifStatement();
                                                 {if (true) return conditionalStatementNode;}
    throw new Error("Missing return statement in function");
  }

//ifÊñ?:=
//	'if' '(' Âº?')' Êñ?['else' Êñá]
  final public StatementNode ifStatement() throws ParseException {
        Token token = null;
        ExpressionNode conditional = null;
        StatementNode thenBody = null;
        StatementNode elseBody = null;
    token = jj_consume_token(IF);
    jj_consume_token(17);
    conditional = expression();
    jj_consume_token(18);
    thenBody = statement();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE:
      jj_consume_token(ELSE);
      elseBody = statement();
      break;
    default:
      jj_la1[8] = jj_gen;
      ;
    }
          {if (true) return new IfNode(new Location(this.getFileName(), token), conditional, thenBody, elseBody);}
    throw new Error("Missing return statement in function");
  }

//Áπ∞„ÇäËøî„ÅóÊñ?:=
//	whileÊñ?
//	|forÊñ?
  final public StatementNode iterationStatement() throws ParseException {
        StatementNode iterationStatement = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case WHILE:
      iterationStatement = whileStatement();
                                                {if (true) return iterationStatement;}
      break;
    case FOR:
      iterationStatement = forStatement();
                                              {if (true) return iterationStatement;}
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

//whileÊñ?:=
//	'while' '(' Âº?')' Êñ?
  final public StatementNode whileStatement() throws ParseException {
        Token token = null;
        ExpressionNode conditional = null;
        StatementNode body = null;
    token = jj_consume_token(WHILE);
    jj_consume_token(17);
    conditional = expression();
    jj_consume_token(18);
    body = statement();
                                                                          {if (true) return new WhileNode(new Location(this.getFileName(), token), conditional, body);}
    throw new Error("Missing return statement in function");
  }

//forÊñ?:=
//	'for' '(' [Âºè] ';' [Âºè] ';' [Âºè] ')' Êñ?
//ÂàùÊúüÂåñÈÉ®„Ç?õ¥Êñ∞ÈÉ®„ÅßË§?ï∞„ÅÆÂºèÊñá„ÇíÂÆüË°åÂ?Êù•„Çã„Çà„Å?Åô„Çã„Åπ„Åç„Åã
  final public StatementNode forStatement() throws ParseException {
        Token token = null;
        ExpressionNode initialize = null;
        ExpressionNode conditional = null;
        ExpressionNode update = null;
        StatementNode body = null;
    token = jj_consume_token(FOR);
    jj_consume_token(17);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
    case INTEGER:
    case STRING:
    case 17:
    case 35:
    case 39:
    case 40:
    case 41:
      initialize = expression();
      break;
    default:
      jj_la1[10] = jj_gen;
      ;
    }
    jj_consume_token(21);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
    case INTEGER:
    case STRING:
    case 17:
    case 35:
    case 39:
    case 40:
    case 41:
      conditional = expression();
      break;
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    jj_consume_token(21);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
    case INTEGER:
    case STRING:
    case 17:
    case 35:
    case 39:
    case 40:
    case 41:
      update = expression();
      break;
    default:
      jj_la1[12] = jj_gen;
      ;
    }
    jj_consume_token(18);
    body = statement();
          {if (true) return new ForNode(new Location(this.getFileName(), token), initialize, conditional, update, body);}
    throw new Error("Missing return statement in function");
  }

//breakÊñ?:=
//	'break' ';'
  final public StatementNode breakStatement() throws ParseException {
        Token token = null;
    token = jj_consume_token(BREAK);
    jj_consume_token(21);
                            {if (true) return new BreakNode(new Location(this.getFileName(), token));}
    throw new Error("Missing return statement in function");
  }

//returnÊñ?:=
//	'return' [Âºè] ';'
  final public StatementNode returnStatement() throws ParseException {
        Token token = null;
        ExpressionNode expressionNode = null;
    token = jj_consume_token(RETURN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
    case INTEGER:
    case STRING:
    case 17:
    case 35:
    case 39:
    case 40:
    case 41:
      expressionNode = expression();
      break;
    default:
      jj_la1[13] = jj_gen;
      ;
    }
    jj_consume_token(21);
                                                           {if (true) return new ReturnNode(new Location(this.getFileName(), token), expressionNode);}
    throw new Error("Missing return statement in function");
  }

//Á©∫Êñ?:=
//	';'
//„ÅÇ„Å®„ÅßË¶ãÁõ¥„Å?
  final public StatementNode emptyStatement() throws ParseException {
        Token token = null;
    token = jj_consume_token(21);
                    {if (true) return new EmptyStatementNode(new Location(this.getFileName(), token));}
    throw new Error("Missing return statement in function");
  }

//ÂºèÊñá :=
//	Âº?';'
  final public ExpressionStatementNode expressionStatement() throws ParseException {
        Token token = null;
        ExpressionNode expressionNode = null;
    //Ë¶Å‰øÆÊ≠£„ÄÇÂºè„?„Ç≥„É≥„Çπ„Éà„É©„ÇØ„Çø„Å®„É°„ÇΩ„É?Éâ„ÇíËøΩÂä?Åó„Å¶„Åã„ÇâÊõ∏„ÅçÊèõ„Åà„Çã
            expressionNode = expression();
    token = jj_consume_token(21);
                                                {if (true) return new ExpressionStatementNode(new Location(this.getFileName(), token), expressionNode);}
    throw new Error("Missing return statement in function");
  }

//Âºè„?ÊßãÊñá
//ÊºîÁÆóÂ≠ê„?ÂÑ™ÂÖàÈ?‰Ωç„Åå‰Ωé„ÅÑÈ†?Å´Êõ∏„Å?

//‰ª£ÂÖ•Âº?
  final public ExpressionNode expression() throws ParseException {
        ExpressionNode left = null;
        ExpressionNode right = null;
        ExpressionNode expressionNode = null;
    if (jj_2_4(2147483647)) {
      left = term();
      jj_consume_token(20);
      right = expression();
                        {if (true) return new AssignNode(left, right);}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
      case INTEGER:
      case STRING:
      case 17:
      case 35:
      case 39:
      case 40:
      case 41:
        expressionNode = expression5();
                        {if (true) return expressionNode;}
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

//Ë´ñÁêÜOR
  final public ExpressionNode expression5() throws ParseException {
        ExpressionNode left = null;
        ExpressionNode right = null;
    left = expression4();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 26:
        ;
        break;
      default:
        jj_la1[15] = jj_gen;
        break label_5;
      }
      jj_consume_token(26);
      right = expression4();
                                                       left = new LogicalOrNode(left, right);
    }
                                                                {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

//Ë´ñÁêÜAND
  final public ExpressionNode expression4() throws ParseException {
        ExpressionNode left = null;
        ExpressionNode right = null;
    left = expression3();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 27:
        ;
        break;
      default:
        jj_la1[16] = jj_gen;
        break label_6;
      }
      jj_consume_token(27);
      right = expression3();
                                                       left = new LogicalAndNode(left, right);
    }
                                                                {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

//ÂêåÁ≠âÂº?
//Èñ¢‰øÇÂº?
  final public ExpressionNode expression3() throws ParseException {
        ExpressionNode left = null;
        ExpressionNode right = null;
    left = expression2();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 28:
      case 29:
      case 30:
      case 31:
      case 32:
      case 33:
        ;
        break;
      default:
        jj_la1[17] = jj_gen;
        break label_7;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 28:
        jj_consume_token(28);
        right = expression2();
                                                        left = new EquivalenceNode(left, right);
        break;
      case 29:
        jj_consume_token(29);
        right = expression2();
                                                                        left = new NotEquivalenceNode(left, right);
        break;
      case 30:
        jj_consume_token(30);
        right = expression2();
                                                                        left = new LessThanNode(left, right);
        break;
      case 31:
        jj_consume_token(31);
        right = expression2();
                                                                        left = new GreaterThanNode(left, right);
        break;
      case 32:
        jj_consume_token(32);
        right = expression2();
                                                                        left = new LessThanOrEqualNode(left, right);
        break;
      case 33:
        jj_consume_token(33);
        right = expression2();
                                                                        left = new GreaterThanOrEqualNode(left, right);
        break;
      default:
        jj_la1[18] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
                                                                {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

//Âä?ÆóÂº?
//Ê∏õÁÆóÂº?
  final public ExpressionNode expression2() throws ParseException {
        ExpressionNode left = null;
        ExpressionNode right = null;
    left = expression1();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 34:
      case 35:
        ;
        break;
      default:
        jj_la1[19] = jj_gen;
        break label_8;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 34:
        jj_consume_token(34);
        right = expression1();
                                                        left = new PlusNode(left, right);
        break;
      case 35:
        jj_consume_token(35);
        right = expression1();
                                                                            left = new MinusNode(left, right);
        break;
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
                                                                {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

//‰πóÁÆóÂº?
//Èô§ÁÆóÂº?
//Ââ∞‰ΩôÂº?
  final public ExpressionNode expression1() throws ParseException {
        ExpressionNode left = null;
        ExpressionNode right = null;
    left = term();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 36:
      case 37:
      case 38:
        ;
        break;
      default:
        jj_la1[21] = jj_gen;
        break label_9;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 36:
        jj_consume_token(36);
        right = term();
                                         left = new MulNode(left, right);
        break;
      case 37:
        jj_consume_token(37);
        right = term();
                                                     left = new DivNode(left, right);
        break;
      case 38:
        jj_consume_token(38);
        right = term();
                                                     left = new ModNode(left, right);
        break;
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
                                                {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

//È†??ÊßãÊñá
  final public ExpressionNode term() throws ParseException {
        ExpressionNode expressionNode = null;
    expressionNode = unaryExpression();
                                           {if (true) return expressionNode;}
    throw new Error("Missing return statement in function");
  }

//ÂçòÈ?Âº?
  final public ExpressionNode unaryExpression() throws ParseException {
        Token token = null;
        ExpressionNode expressionNode = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 39:
      token = jj_consume_token(39);
      expressionNode = unaryExpression();
                                                        {if (true) return new PreIncrementNode(expressionNode);}
      break;
    case 40:
      token = jj_consume_token(40);
      expressionNode = unaryExpression();
                                                        {if (true) return new PreDecrementNode(expressionNode);}
      break;
    case 35:
      token = jj_consume_token(35);
      expressionNode = unaryExpression();
                                                       {if (true) return new UnaryMinusNode(expressionNode);}
      break;
    case 41:
      token = jj_consume_token(41);
      expressionNode = unaryExpression();
                                                       {if (true) return new ExclamationNode(expressionNode);}
      break;
    case IDENTIFIER:
    case INTEGER:
    case STRING:
    case 17:
      expressionNode = PostfixExpression();
                                               {if (true) return expressionNode;}
      break;
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

//ÂæåÁΩÆÂº?
  final public ExpressionNode PostfixExpression() throws ParseException {
        Token token = null;
        ExpressionNode expressionNode = null;
        IdentifierNode arrayName = null;
        ExpressionNode index = null;
        List<ExpressionNode> arguments = null;
    expressionNode = primaryExpression();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 17:
      case 22:
      case 39:
      case 40:
        ;
        break;
      default:
        jj_la1[24] = jj_gen;
        break label_10;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 39:
        token = jj_consume_token(39);
                       expressionNode = new PostIncrementNode(expressionNode);
        break;
      case 40:
        token = jj_consume_token(40);
                       expressionNode = new PostDecrementNode(expressionNode);
        break;
      case 22:
        token = jj_consume_token(22);
        index = expression();
        jj_consume_token(23);
                        arrayName = (IdentifierNode)expressionNode;
                        expressionNode = new ArraySubscriptExpressionNode(arrayName, index); //Ê∑ªÂ≠óÂº?

        break;
      case 17:
        token = jj_consume_token(17);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENTIFIER:
        case INTEGER:
        case STRING:
        case 17:
        case 35:
        case 39:
        case 40:
        case 41:
          arguments = arguments();
          break;
        default:
          jj_la1[25] = jj_gen;
          ;
        }
        jj_consume_token(18);
                                                  expressionNode = new CallNode(expressionNode, arguments);
        break;
      default:
        jj_la1[26] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
                        {if (true) return expressionNode;}
    throw new Error("Missing return statement in function");
  }

//ÂºïÊï∞
  final public List<ExpressionNode> arguments() throws ParseException {
        List<ExpressionNode> arguments = new LinkedList<ExpressionNode>();
        ExpressionNode argument = null;
    argument = expression();
                                arguments.add(argument);
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 19:
        ;
        break;
      default:
        jj_la1[27] = jj_gen;
        break label_11;
      }
      jj_consume_token(19);
      argument = expression();
                                     arguments.add(argument);
    }
                        {if (true) return arguments;}
    throw new Error("Missing return statement in function");
  }

//‰∏?¨°Âº?
  final public ExpressionNode primaryExpression() throws ParseException {
        Token token = null;
        ExpressionNode expressionNode = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTEGER:
      token = jj_consume_token(INTEGER);
                                {if (true) return new LiteralNode(new Location(this.getFileName(), token), DataType.INT, token.image);}
      break;
    case STRING:
      token = jj_consume_token(STRING);
                                {if (true) return new LiteralNode(new Location(this.getFileName(), token), DataType.STRING, token.image);}
      break;
    case IDENTIFIER:
      token = jj_consume_token(IDENTIFIER);
                                {if (true) return new IdentifierNode(new Location(this.getFileName(), token), token.image);}
      break;
    case 17:
      jj_consume_token(17);
      expressionNode = expression();
      jj_consume_token(18);
                                {if (true) return expressionNode;}
      break;
    default:
      jj_la1[28] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_3R_14() {
    if (jj_3R_12()) return true;
    return false;
  }

  private boolean jj_3R_40() {
    if (jj_scan_token(17)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_43()) jj_scanpos = xsp;
    if (jj_scan_token(18)) return true;
    return false;
  }

  private boolean jj_3R_36() {
    if (jj_scan_token(26)) return true;
    if (jj_3R_35()) return true;
    return false;
  }

  private boolean jj_3R_39() {
    if (jj_scan_token(22)) return true;
    if (jj_3R_24()) return true;
    if (jj_scan_token(23)) return true;
    return false;
  }

  private boolean jj_3R_38() {
    if (jj_scan_token(40)) return true;
    return false;
  }

  private boolean jj_3R_34() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_37()) {
    jj_scanpos = xsp;
    if (jj_3R_38()) {
    jj_scanpos = xsp;
    if (jj_3R_39()) {
    jj_scanpos = xsp;
    if (jj_3R_40()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_37() {
    if (jj_scan_token(39)) return true;
    return false;
  }

  private boolean jj_3R_35() {
    if (jj_3R_41()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_42()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_32() {
    if (jj_3R_13()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_34()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_2() {
    if (jj_scan_token(19)) return true;
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3R_33() {
    if (jj_3R_35()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_36()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_3R_32()) return true;
    return false;
  }

  private boolean jj_3R_28() {
    if (jj_scan_token(41)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_scan_token(35)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_61() {
    if (jj_scan_token(38)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3R_26() {
    if (jj_scan_token(40)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_60() {
    if (jj_scan_token(37)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3R_23() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_25()) {
    jj_scanpos = xsp;
    if (jj_3R_26()) {
    jj_scanpos = xsp;
    if (jj_3R_27()) {
    jj_scanpos = xsp;
    if (jj_3R_28()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_scan_token(39)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_58() {
    if (jj_scan_token(35)) return true;
    if (jj_3R_47()) return true;
    return false;
  }

  private boolean jj_3_4() {
    if (jj_3R_15()) return true;
    if (jj_scan_token(20)) return true;
    return false;
  }

  private boolean jj_3R_31() {
    if (jj_3R_33()) return true;
    return false;
  }

  private boolean jj_3R_24() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_30()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) return true;
    }
    return false;
  }

  private boolean jj_3R_30() {
    if (jj_3R_15()) return true;
    if (jj_scan_token(20)) return true;
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_15() {
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_59() {
    if (jj_scan_token(36)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3R_56() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_59()) {
    jj_scanpos = xsp;
    if (jj_3R_60()) {
    jj_scanpos = xsp;
    if (jj_3R_61()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_18() {
    if (jj_scan_token(VOID)) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_scan_token(INT)) return true;
    if (jj_scan_token(22)) return true;
    return false;
  }

  private boolean jj_3R_17() {
    if (jj_scan_token(INT)) return true;
    return false;
  }

  private boolean jj_3R_57() {
    if (jj_scan_token(34)) return true;
    if (jj_3R_47()) return true;
    return false;
  }

  private boolean jj_3R_54() {
    if (jj_scan_token(33)) return true;
    if (jj_3R_44()) return true;
    return false;
  }

  private boolean jj_3R_48() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_57()) {
    jj_scanpos = xsp;
    if (jj_3R_58()) return true;
    }
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_12()) return true;
    if (jj_3R_13()) return true;
    if (jj_scan_token(17)) return true;
    return false;
  }

  private boolean jj_3R_53() {
    if (jj_scan_token(32)) return true;
    if (jj_3R_44()) return true;
    return false;
  }

  private boolean jj_3R_52() {
    if (jj_scan_token(31)) return true;
    if (jj_3R_44()) return true;
    return false;
  }

  private boolean jj_3R_51() {
    if (jj_scan_token(30)) return true;
    if (jj_3R_44()) return true;
    return false;
  }

  private boolean jj_3R_16() {
    if (jj_scan_token(INT)) return true;
    if (jj_scan_token(22)) return true;
    if (jj_3R_24()) return true;
    if (jj_scan_token(23)) return true;
    return false;
  }

  private boolean jj_3R_12() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_16()) {
    jj_scanpos = xsp;
    if (jj_3R_17()) {
    jj_scanpos = xsp;
    if (jj_3R_18()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_50() {
    if (jj_scan_token(29)) return true;
    if (jj_3R_44()) return true;
    return false;
  }

  private boolean jj_3R_47() {
    if (jj_3R_15()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_56()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_22() {
    if (jj_scan_token(17)) return true;
    if (jj_3R_24()) return true;
    if (jj_scan_token(18)) return true;
    return false;
  }

  private boolean jj_3R_21() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_20() {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  private boolean jj_3R_49() {
    if (jj_scan_token(28)) return true;
    if (jj_3R_44()) return true;
    return false;
  }

  private boolean jj_3R_45() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3R_50()) {
    jj_scanpos = xsp;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) {
    jj_scanpos = xsp;
    if (jj_3R_53()) {
    jj_scanpos = xsp;
    if (jj_3R_54()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_44() {
    if (jj_3R_47()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_48()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_19() {
    if (jj_scan_token(INTEGER)) return true;
    return false;
  }

  private boolean jj_3R_13() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_19()) {
    jj_scanpos = xsp;
    if (jj_3R_20()) {
    jj_scanpos = xsp;
    if (jj_3R_21()) {
    jj_scanpos = xsp;
    if (jj_3R_22()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_55() {
    if (jj_scan_token(19)) return true;
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_46() {
    if (jj_3R_24()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_55()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_42() {
    if (jj_scan_token(27)) return true;
    if (jj_3R_41()) return true;
    return false;
  }

  private boolean jj_3R_43() {
    if (jj_3R_46()) return true;
    return false;
  }

  private boolean jj_3R_41() {
    if (jj_3R_44()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_45()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  /** Generated Token Manager. */
  public C0LanguageTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[29];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xc,0xc,0xc,0x100000,0xc,0x1230fd0,0x1230fd0,0xc,0x20,0xc0,0x30c00,0x30c00,0x30c00,0x30c00,0x30c00,0x4000000,0x8000000,0xf0000000,0xf0000000,0x0,0x0,0x0,0x0,0x30c00,0x420000,0x30c00,0x420000,0x80000,0x30c00,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x0,0x388,0x388,0x0,0x0,0x0,0x388,0x388,0x388,0x388,0x388,0x0,0x0,0x3,0x3,0xc,0xc,0x70,0x70,0x388,0x180,0x388,0x180,0x0,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[4];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public C0Language(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public C0Language(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new C0LanguageTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 29; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 29; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public C0Language(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new C0LanguageTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 29; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 29; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public C0Language(C0LanguageTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 29; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(C0LanguageTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 29; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[42];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 29; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 42; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 4; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
